### ISSUE TITLE
Ideas for the site

### ISSUE THREAD

**Issue by Lbatson** [LearnProgramming/lpmc-site#1]
Copied notes from raylu, bolcselo, darkf, myself

LPMC Mentoring Site Idea Bank

Features:
- Student registration; students get placed into a pool of users awaiting mentors
  - contact methods with the mentees? mailing list or some way to contact maybe?
- Mentors can select from a student pool and put students into their group/project
  - This would imply that mentors and students have some way to know about each other and why they might/might not be a good match.
- We should maintain a current list of projects.
  - For each project there should be a list of small tasks that students can do to contribute.
- Instead of a large community of people to help with a particular problem (something the subreddit accomplishes already) there should be subcommunites based on language or project, or both. 
  - The IRC just ends up being a resource for people who dont want to wait for their post to get answered, then disappear forever.
- Some sort of ranks, I guess? 
- reddit itself can let an admin assign flairs in a particular subreddit
- reddit also has badges. don't know if subreddit admins can dole them out though... /u/lovewithacaveat from /r/computingscience has a badge system worked out over there
  - i think its muscle driven though <you like my new cool phrase?
    - we've been talking about making an achievements/badges webapp
- github OAuth or reddit OAuth?
  - Both? GitHub ensures they have a valid account, though
- vetting/certifying mentors?
  - some sort of testing it would "auto-vet" future mentors. that way people can prove a certain level of proficency in one area or another to be a mentor. This could also tie into the idea of gamification. As users pass certain levels they're "certified" in certain areas and would be able to mentor others through them.

**Comment by jfredett** [comment]
I don't know that this requires a new issue -- but I noticed the frontpage links to /r/learnprogramming and #learnprogramming, and not to /r/lpmc and #lpmc, the former is perhaps not a big deal, but the latter might be worth linking too, given that's where we all hang out + have been telling people to go for the last 2 years.

**Comment by Lbatson** [comment]
good point. yea we linked to learnprogramming as it's in the sidebar there, so like crossover i guess. Maybe having both there and some of the info about how lpmc came about etc?

**Comment by jfredett** [comment]
I’m for having both, /r/learnprogramming kicks ass, and everyone should go there, LPMC just had some stuff separate to keep the signal/noise ratio high in LP-proper.
