### ISSUE TITLE
Add `nickname` to `users` table.

### ISSUE THREAD

**Issue by Robert-Wett** [LearnProgramming/lpmc-site#9]
Just for people like me who use different names in IRC vs. GitHub, it would be nice to have the optional ability to add a nickname to show beside/under your username either in your account or in the /users view.

**Comment by Lbatson** [comment]
good idea. +1

**Comment by ZachMassia** [comment]
@intothev01d have you been working on this? 

I'm just reading through everything right now to get an idea how things are set up. If no one is working on this I'll probably start on it tomorrow.

**Comment by Lbatson** [comment]
no i'm not working on it. sounds good.

**Comment by Robert-Wett** [comment]
@ZachMassia : I'm supposed to be working on this, and while I have a little bit of work against this I'm moving way too slow. You can take over on this one and I'll focus on adding the `Notes` feature.

**Comment by ZachMassia** [comment]
@raylu This issue can be closed now.
